<a href="https://colab.research.google.com/github/Seby8/Numerical_Methods/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and Its Operations

In [8]:
import numpy as np

a = np.array([
              [-5,0],
              [4,1]
])

b = np.array([
              [6,-3],
              [2,3]
])

sum = a + b
difference1 = b - a
difference2 = a - b
print(f'Using Sum:\n{sum}')
print(f'Using Difference 1:\n{difference1}')
print(f'Using Difference 2:\n{difference2}')

Using Sum:
[[ 1 -3]
 [ 6  4]]
Using Difference 1:
[[11 -3]
 [-2  2]]
Using Difference 2:
[[-11   3]
 [  2  -2]]
